  ;; -----------------------------------------------------------------
  ;;
  ;; Interrupt Descriptor Table
  ;; ==========================
  ;;
  ;; Interrupts and exceptions are events that indicate that a
  ;; condition exists somewhere in the system, the processor, or
  ;; within the currently executing program or task that requires the
  ;; attention of a processor. They typically result in a forced
  ;; transfer of execution from the currently running program or task
  ;; to a special software routine or task called an interrupt handler
  ;; or an exception handler. The action taken by a processor in
  ;; response to an interrupt or exception is referred to as servicing
  ;; or handling the interrupt or exception.
  ;; 
  ;; The interrupt descriptor table (IDT) specifies to the CPU where
  ;; the Interrupt Service Routines are located. Its entries are
  ;; called gates, which can be of the following types:
  ;;
  ;;  - *interrupt*: used to specify an interrupt service routine,
  ;;      they are generated at random times during the execution of a
  ;;      program, in response from signals from hardware.
  ;; 
  ;;  - *trap*: used to handle exceptions which are generated by the
  ;;      CPU when an error condition is detected, such as division by
  ;;      0.
  ;; 
  ;;      Exceptions are further classified as:
  ;; 
  ;;        - *faults*: an exception that can be generally be
  ;;             corrected and that, once corrected, allows the
  ;;             program to be restarted with no loss of continuity.
  ;; 
  ;;        - *traps*: an exception that is reported immediately
  ;;             following the execution of the trapping instruciton.
  ;; 
  ;;        - *abort*: an exception that does not always report the
  ;;             precise location of the instruction causing the
  ;;             exception
  ;; 
  ;;  - *task: used for hardware taks switching (removed in x86_64)
  ;;
  ;; 
  ;; Location
  ;; --------
  ;; 
  ;; The location of the IDT is kept in IDTR (IDT register) which is
  ;; loaded using the LIDT assembly instruciton, whose argument is a
  ;; pointer to an IDT descriptor structure:
  ;;
  ;;                    + ------------------ +
  ;;                    | 79 -- 16 | 15 -- 0 |
  ;;                    | ======== | ======= |
  ;;                    | offset   | size    |
  ;;                    + ------------------ +
  ;; 
  ;; Where size is one less than the size of the IDT is bytes, and
  ;; offset is the linear address of the IDT (not the physical
  ;; address, paging applies).
  ;;
  ;;
  ;; Table
  ;; -----
  ;;
  ;; There are 256 interrupt vectors, so the IDT should have 256
  ;; entries (gates), each gate corresponding to a specific interrupt
  ;; vector.
  ;; 
  ;; On 64-bit processors, the entries in the IDT are 16 bytes long
  ;; and form a table like this:
  ;;
  ;;              + ------------------------------ +
  ;;              | Address            | Content   |
  ;;              | ================== | ========= |
  ;;              | IDTR Offset + 0    | Entry 0   |
  ;;              | IDTR Offset + 16   | Entry 1   |
  ;;              | IDTR Offset + 32   | Entry 2   |
  ;;              | ...                | ...       |
  ;;              | IDTR Offset + 4080 | Entry 255 |
  ;;              + ------------------------------ +
  ;;
  ;; The corresponsing entry for a given interrupt vector is pointed
  ;; to in memory by scaling the vector by 16 and adding it to the
  ;; value in the offset field in the IDTR.
  ;;
  ;; 
  ;; Gates
  ;; -----
  ;;
  ;; A gate in the table has the following structure (using C for
  ;; clarity):
  ;;
  ;;   struct InterruptGate64 {
  ;;     uint16_t offset_1;        // offset bits 0..15
  ;;     uint16_t selector;        // a code segment selector in GDT
  ;;                               // or LDT
  ;;     uint8_t  ist;             // bits 0..2 holds Interrupt Stack
  ;;                               // Table offset, rest of bits zero.
  ;;     uint8_t  type_attributes; // Gate Type, Dpl, and P fields
  ;;     uint16_t offset_2;        // offset bits 16..31
  ;;     uint32_t offset_3;        // offset bits 32..63
  ;;     uint32_t zero;            // reserved
  ;;   };
  ;;
  ;; The Gate Type is a 4-bit value which defines the type of gate
  ;; this Interrupt Descriptor represents. In long mode there are two
  ;; valid type values:
  ;; 
  ;;   - 0b1110 or 0xE: 64-bit Interrupt Gate
  ;;   - 0b1111 or 0xF: 64-bit Trap Gate
  ;; 
  ;; DPL is a 2-bit value which defines the CPU Privilege Levels which
  ;; are allowed to access this interrupt via the INT
  ;; instruction. Hardware interrupts ignore this mechanism.
  ;;
  ;; P is the present bit. Must be set (1) for the descriptor to be
  ;; valid.
  ;;
  ;; 
  ;; Interrupt Service Routines
  ;; --------------------------
  ;;
  ;; Interrupt Service Routines must return from the interrupt using
  ;; the 'iretq' instruction.
  ;;
  ;; When the CPU calls the interrupt handlers, it changes the value
  ;; of the stack pointer to the IST (if specified). It then pushes
  ;; these values in this order: SS:RSP (original stack pointer),
  ;; RFLAGS, CS (code segment), RIP. CS is padded to form a quadword.
  ;; 
  ;; If the interrupt is an exception, the CPU will push an error code
  ;; onto the stack, padded with bytes to form a quadword.
  ;;
  ;;
  ;; List of interrupts
  ;; ------------------
  ;;
  ;; Here is a list of some exceptions and interrupts for x86_64:
  ;;
  ;; + ----------------------------------------------------------------- +
  ;; | Num  | Type       | Name            | Source                      |
  ;; | ==== | ========== | =============== | =========================== |
  ;; | 0x00 | Fault      | Divide Error    | Integer divide instructions |
  ;; | 0x01 | Trap/Fault | Debug Exception | Instruction, data, and I/0  |
  ;; |      |            |                 | breakpoints.                |
  ;; | 0x02 | Interrupt  | NMI Interrupt   | Nonmaskable external irq.   |
  ;; | 0x03 | Trap       | Breakpoint      | int3 instruction            |
  ;; | 0x04 | Trap       | Overflow        | int0 instruciton            |
  ;; | ...  | ...        | ...             | ...                         |
  ;; + ----------------------------------------------------------------- +
  ;;
  ;; For the full list goto the Intel manual, Volume 3 chapter 7.
  ;; 
  
  [bits 64]

  section .bss

 align 16
idt_start:                      ; a single entry is 16 bytes
     resb 256 * 16              ; 0 initialized
idt_end:

  section .data
  
gate:
  dq 2
  
idt_register:
    dw idt_end - idt_start - 1  ; limit (16 bits)
    dq idt_start                ; base  (64 bits)

  section .text
  
  ;; -----------------------------------------------------------------
  ;; Load the IDT, disabled interrupts
load_idt:
  lidt [idt_register]
  ret
