OBJ += kernel/main.o \
       kernel/utils.o \
       kernel/isr.o \
       kernel/idt.o \
       kernel/debug.o \
       kernel/isr_string.o \
       kernel/textbuffer.o \
       kernel/tty.o \
       kernel/banner.o \
       kernel/framebuffer.o \
       kernel/time.o \
       kernel/task.o \
       kernel/sched.o \
       kernel/sync.o \
       kernel/gdt.o 

include kernel/input/make.conf
