OBJ += drivers/uart.o \
       drivers/ps2.o \
       drivers/pic.o \
       drivers/pit.o

include drivers/acpi/make.conf
include drivers/pci/make.conf
include drivers/isa/make.conf
include drivers/video/make.conf
include drivers/input/make.conf