OBJ += drivers/uart.o \
       drivers/ps2.o \
       drivers/pic.o \
       drivers/pit.o \
       drivers/acpi.o \
       drivers/pci.o \
       drivers/hpet.o \
       drivers/edu.o \
       drivers/isa.o
  